version: '2'
services:
  web:
    command: rails s
    depends_on:
      - pg
    image: vk1
    links:
      - pg:postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/source
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  # redis:
  #   image: redis