redis:
  uri: http://localhost:6379/
aws:
  access_key_id: OVERRIDE_ME
  secret_access_key: OVERRIDE_ME
hasher:
  secret_key: OVERRIDE_ME
google_analytics:
  analytics_id: UA-31572927-1
email:
  from_address: Melanie Jones <info@watchdog.net>
dp_connection:
  host: OVERRIDE_ME
  username: OVERRIDE_ME
  password: OVERRIDE_ME
  database: OVERRIDE_ME
cloudmailin:
  token: <%= ENV["CLOUDMAILIN_TOKEN"] %>
organization:
  name: "Demand Progress"
  email: "info@demandprogress.org"
  unsubscribe_url: "https://act.demandprogress.org/unsubscribe/unsubscribe?source=watchdog"
  logo: 'logo.png'
site:
  name: "Watchdog.net"
  email: "support@watchdog.net"
  hostname: "act.watchdog.net"
  feedback_email: info+watchdog@demandprogress.org
  list_unsubscribe: "unsubscribe@appmail.watchdog.net"
