redis:
  uri: http://localhost:6379
aws:
  access_key_id: OVERRIDE_ME
  secret_access_key: OVERRIDE_ME
hasher:
  secret_key: victorize
google_analytics:
   analytics_id: UA-31218452-1
email:
   from_address: info@watchdog.net

