production: &default
  facebook:
    app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    site_name: Victory Kit
    image: http://act.watchdog.net/images/petition-fb.png
      
test: *default
    
development: *default
